export const normalStatus = {
    male: [
        {
            age: 1,
            normal_height_median: 54.7,
            stunting_threshold: 49.9,
            malnutrition_weight: 2.6,
            obesity_weight: 4.8,
        },
        {
            age: 2,
            normal_height_median: 57.3,
            stunting_threshold: 52.4,
            malnutrition_weight: 2.8,
            obesity_weight: 5.1,
        },
        {
            age: 3,
            normal_height_median: 59.9,
            stunting_threshold: 54.8,
            malnutrition_weight: 3.0,
            obesity_weight: 5.4,
        },
        {
            age: 4,
            normal_height_median: 62.4,
            stunting_threshold: 57.3,
            malnutrition_weight: 3.1,
            obesity_weight: 5.7,
        },
        {
            age: 5,
            normal_height_median: 65.0,
            stunting_threshold: 59.7,
            malnutrition_weight: 3.2,
            obesity_weight: 6.0,
        },
        {
            age: 6,
            normal_height_median: 67.6,
            stunting_threshold: 62.2,
            malnutrition_weight: 3.4,
            obesity_weight: 6.3,
        },
        {
            age: 7,
            normal_height_median: 68.9,
            stunting_threshold: 63.5,
            malnutrition_weight: 3.5,
            obesity_weight: 6.6,
        },
        {
            age: 8,
            normal_height_median: 70.3,
            stunting_threshold: 64.8,
            malnutrition_weight: 3.7,
            obesity_weight: 6.9,
        },
        {
            age: 9,
            normal_height_median: 71.7,
            stunting_threshold: 66.2,
            malnutrition_weight: 3.8,
            obesity_weight: 7.2,
        },
        {
            age: 10,
            normal_height_median: 73.0,
            stunting_threshold: 67.5,
            malnutrition_weight: 4.0,
            obesity_weight: 7.5,
        },
        {
            age: 11,
            normal_height_median: 74.3,
            stunting_threshold: 68.8,
            malnutrition_weight: 4.2,
            obesity_weight: 7.8,
        },
        {
            age: 12,
            normal_height_median: 75.7,
            stunting_threshold: 70.1,
            malnutrition_weight: 4.3,
            obesity_weight: 8.1,
        },
        {
            age: 13,
            normal_height_median: 76.6,
            stunting_threshold: 71.0,
            malnutrition_weight: 4.5,
            obesity_weight: 8.4,
        },
        {
            age: 14,
            normal_height_median: 77.6,
            stunting_threshold: 71.9,
            malnutrition_weight: 4.6,
            obesity_weight: 8.7,
        },
        {
            age: 15,
            normal_height_median: 78.5,
            stunting_threshold: 72.8,
            malnutrition_weight: 4.8,
            obesity_weight: 9.0,
        },
        {
            age: 16,
            normal_height_median: 79.5,
            stunting_threshold: 73.7,
            malnutrition_weight: 4.9,
            obesity_weight: 9.3,
        },
        {
            age: 17,
            normal_height_median: 80.4,
            stunting_threshold: 74.6,
            malnutrition_weight: 5.0,
            obesity_weight: 9.6,
        },
        {
            age: 18,
            normal_height_median: 81.3,
            stunting_threshold: 75.5,
            malnutrition_weight: 5.2,
            obesity_weight: 9.9,
        },
        {
            age: 19,
            normal_height_median: 82.3,
            stunting_threshold: 76.5,
            malnutrition_weight: 5.3,
            obesity_weight: 10.2,
        },
        {
            age: 20,
            normal_height_median: 83.2,
            stunting_threshold: 77.4,
            malnutrition_weight: 5.5,
            obesity_weight: 10.5,
        },
        {
            age: 21,
            normal_height_median: 84.2,
            stunting_threshold: 78.3,
            malnutrition_weight: 5.7,
            obesity_weight: 10.8,
        },
        {
            age: 22,
            normal_height_median: 85.1,
            stunting_threshold: 79.2,
            malnutrition_weight: 5.8,
            obesity_weight: 11.1,
        },
        {
            age: 23,
            normal_height_median: 86.1,
            stunting_threshold: 80.1,
            malnutrition_weight: 5.9,
            obesity_weight: 11.4,
        },
        {
            age: 24,
            normal_height_median: 87.0,
            stunting_threshold: 81.0,
            malnutrition_weight: 6.1,
            obesity_weight: 11.7,
        },
        {
            age: 25,
            normal_height_median: 87.8,
            stunting_threshold: 81.7,
            malnutrition_weight: 6.2,
            obesity_weight: 12.0,
        },
        {
            age: 26,
            normal_height_median: 88.5,
            stunting_threshold: 82.4,
            malnutrition_weight: 6.4,
            obesity_weight: 12.3,
        },
        {
            age: 27,
            normal_height_median: 89.2,
            stunting_threshold: 83.1,
            malnutrition_weight: 6.5,
            obesity_weight: 12.6,
        },
        {
            age: 28,
            normal_height_median: 90.0,
            stunting_threshold: 83.8,
            malnutrition_weight: 6.7,
            obesity_weight: 12.9,
        },
        {
            age: 29,
            normal_height_median: 90.8,
            stunting_threshold: 84.5,
            malnutrition_weight: 6.8,
            obesity_weight: 13.2,
        },
        {
            age: 30,
            normal_height_median: 91.5,
            stunting_threshold: 85.2,
            malnutrition_weight: 7.0,
            obesity_weight: 13.5,
        },
        {
            age: 31,
            normal_height_median: 92.2,
            stunting_threshold: 86.0,
            malnutrition_weight: 7.1,
            obesity_weight: 13.8,
        },
        {
            age: 32,
            normal_height_median: 93.0,
            stunting_threshold: 86.7,
            malnutrition_weight: 7.3,
            obesity_weight: 14.1,
        },
        {
            age: 33,
            normal_height_median: 93.8,
            stunting_threshold: 87.4,
            malnutrition_weight: 7.5,
            obesity_weight: 14.4,
        },
        {
            age: 34,
            normal_height_median: 94.5,
            stunting_threshold: 88.1,
            malnutrition_weight: 7.6,
            obesity_weight: 14.7,
        },
        {
            age: 35,
            normal_height_median: 95.2,
            stunting_threshold: 88.8,
            malnutrition_weight: 7.8,
            obesity_weight: 15.0,
        },
        {
            age: 36,
            normal_height_median: 96.0,
            stunting_threshold: 89.5,
            malnutrition_weight: 7.9,
            obesity_weight: 15.3,
        },
        {
            age: 37,
            normal_height_median: 96.6,
            stunting_threshold: 90.0,
            malnutrition_weight: 8.1,
            obesity_weight: 15.6,
        },
        {
            age: 38,
            normal_height_median: 97.2,
            stunting_threshold: 90.6,
            malnutrition_weight: 8.2,
            obesity_weight: 15.9,
        },
        {
            age: 39,
            normal_height_median: 97.8,
            stunting_threshold: 91.1,
            malnutrition_weight: 8.3,
            obesity_weight: 16.2,
        },
        {
            age: 40,
            normal_height_median: 98.3,
            stunting_threshold: 91.7,
            malnutrition_weight: 8.5,
            obesity_weight: 16.5,
        },
        {
            age: 41,
            normal_height_median: 98.9,
            stunting_threshold: 92.2,
            malnutrition_weight: 8.6,
            obesity_weight: 16.8,
        },
        {
            age: 42,
            normal_height_median: 99.5,
            stunting_threshold: 92.8,
            malnutrition_weight: 8.8,
            obesity_weight: 17.1,
        },
        {
            age: 43,
            normal_height_median: 100.1,
            stunting_threshold: 93.3,
            malnutrition_weight: 8.9,
            obesity_weight: 17.4,
        },
        {
            age: 44,
            normal_height_median: 100.7,
            stunting_threshold: 93.8,
            malnutrition_weight: 9.1,
            obesity_weight: 17.7,
        },
        {
            age: 45,
            normal_height_median: 101.2,
            stunting_threshold: 94.4,
            malnutrition_weight: 9.2,
            obesity_weight: 18.0,
        },
        {
            age: 46,
            normal_height_median: 101.8,
            stunting_threshold: 94.9,
            malnutrition_weight: 9.4,
            obesity_weight: 18.3,
        },
        {
            age: 47,
            normal_height_median: 102.4,
            stunting_threshold: 95.5,
            malnutrition_weight: 9.6,
            obesity_weight: 18.6,
        },
        {
            age: 48,
            normal_height_median: 103.0,
            stunting_threshold: 96.0,
            malnutrition_weight: 9.7,
            obesity_weight: 18.9,
        },
        {
            age: 49,
            normal_height_median: 103.6,
            stunting_threshold: 96.3,
            malnutrition_weight: 9.8,
            obesity_weight: 19.2,
        },
        {
            age: 50,
            normal_height_median: 104.2,
            stunting_threshold: 96.7,
            malnutrition_weight: 10.0,
            obesity_weight: 19.5,
        },
        {
            age: 51,
            normal_height_median: 104.8,
            stunting_threshold: 97.0,
            malnutrition_weight: 10.1,
            obesity_weight: 19.8,
        },
        {
            age: 52,
            normal_height_median: 105.3,
            stunting_threshold: 97.3,
            malnutrition_weight: 10.3,
            obesity_weight: 20.1,
        },
        {
            age: 53,
            normal_height_median: 105.9,
            stunting_threshold: 97.7,
            malnutrition_weight: 10.4,
            obesity_weight: 20.4,
        },
        {
            age: 54,
            normal_height_median: 106.5,
            stunting_threshold: 98.0,
            malnutrition_weight: 10.6,
            obesity_weight: 20.7,
        },
        {
            age: 55,
            normal_height_median: 107.1,
            stunting_threshold: 98.3,
            malnutrition_weight: 10.8,
            obesity_weight: 21.0,
        },
        {
            age: 56,
            normal_height_median: 107.7,
            stunting_threshold: 98.7,
            malnutrition_weight: 10.9,
            obesity_weight: 21.3,
        },
        {
            age: 57,
            normal_height_median: 108.2,
            stunting_threshold: 99.0,
            malnutrition_weight: 11.0,
            obesity_weight: 21.6,
        },
        {
            age: 58,
            normal_height_median: 108.8,
            stunting_threshold: 99.3,
            malnutrition_weight: 11.2,
            obesity_weight: 21.9,
        },
        {
            age: 59,
            normal_height_median: 109.4,
            stunting_threshold: 99.7,
            malnutrition_weight: 11.3,
            obesity_weight: 22.2,
        },
        {
            age: 60,
            normal_height_median: 110.0,
            stunting_threshold: 100.0,
            malnutrition_weight: 11.5,
            obesity_weight: 22.5,
        },
    ],
    female: [
        {
            age: 1,
            normal_height_median: 53.7,
            stunting_threshold: 48.9,
            malnutrition_weight: 2.5,
            obesity_weight: 4.7,
        },
        {
            age: 2,
            normal_height_median: 56.1,
            stunting_threshold: 51.2,
            malnutrition_weight: 2.7,
            obesity_weight: 5.0,
        },
        {
            age: 3,
            normal_height_median: 58.5,
            stunting_threshold: 53.5,
            malnutrition_weight: 2.8,
            obesity_weight: 5.2,
        },
        {
            age: 4,
            normal_height_median: 60.9,
            stunting_threshold: 55.9,
            malnutrition_weight: 3.0,
            obesity_weight: 5.5,
        },
        {
            age: 5,
            normal_height_median: 63.3,
            stunting_threshold: 58.2,
            malnutrition_weight: 3.1,
            obesity_weight: 5.8,
        },
        {
            age: 6,
            normal_height_median: 65.7,
            stunting_threshold: 60.5,
            malnutrition_weight: 3.2,
            obesity_weight: 6.1,
        },
        {
            age: 7,
            normal_height_median: 67.1,
            stunting_threshold: 61.9,
            malnutrition_weight: 3.4,
            obesity_weight: 6.4,
        },
        {
            age: 8,
            normal_height_median: 68.5,
            stunting_threshold: 63.3,
            malnutrition_weight: 3.5,
            obesity_weight: 6.6,
        },
        {
            age: 9,
            normal_height_median: 69.8,
            stunting_threshold: 64.7,
            malnutrition_weight: 3.7,
            obesity_weight: 6.9,
        },
        {
            age: 10,
            normal_height_median: 71.2,
            stunting_threshold: 66.1,
            malnutrition_weight: 3.8,
            obesity_weight: 7.2,
        },
        {
            age: 11,
            normal_height_median: 72.6,
            stunting_threshold: 67.5,
            malnutrition_weight: 3.9,
            obesity_weight: 7.5,
        },
        {
            age: 12,
            normal_height_median: 74.0,
            stunting_threshold: 68.9,
            malnutrition_weight: 4.1,
            obesity_weight: 7.8,
        },
        {
            age: 13,
            normal_height_median: 75.0,
            stunting_threshold: 69.8,
            malnutrition_weight: 4.2,
            obesity_weight: 8.0,
        },
        {
            age: 14,
            normal_height_median: 76.0,
            stunting_threshold: 70.6,
            malnutrition_weight: 4.4,
            obesity_weight: 8.3,
        },
        {
            age: 15,
            normal_height_median: 76.9,
            stunting_threshold: 71.5,
            malnutrition_weight: 4.5,
            obesity_weight: 8.6,
        },
        {
            age: 16,
            normal_height_median: 77.9,
            stunting_threshold: 72.3,
            malnutrition_weight: 4.6,
            obesity_weight: 8.9,
        },
        {
            age: 17,
            normal_height_median: 78.9,
            stunting_threshold: 73.2,
            malnutrition_weight: 4.8,
            obesity_weight: 9.2,
        },
        {
            age: 18,
            normal_height_median: 79.8,
            stunting_threshold: 74.1,
            malnutrition_weight: 4.9,
            obesity_weight: 9.4,
        },
        {
            age: 19,
            normal_height_median: 80.8,
            stunting_threshold: 74.9,
            malnutrition_weight: 5.1,
            obesity_weight: 9.7,
        },
        {
            age: 20,
            normal_height_median: 81.8,
            stunting_threshold: 75.8,
            malnutrition_weight: 5.2,
            obesity_weight: 10.0,
        },
        {
            age: 21,
            normal_height_median: 82.8,
            stunting_threshold: 76.6,
            malnutrition_weight: 5.3,
            obesity_weight: 10.3,
        },
        {
            age: 22,
            normal_height_median: 83.8,
            stunting_threshold: 77.5,
            malnutrition_weight: 5.5,
            obesity_weight: 10.6,
        },
        {
            age: 23,
            normal_height_median: 84.7,
            stunting_threshold: 78.3,
            malnutrition_weight: 5.6,
            obesity_weight: 10.8,
        },
        {
            age: 24,
            normal_height_median: 85.7,
            stunting_threshold: 79.2,
            malnutrition_weight: 5.8,
            obesity_weight: 11.1,
        },
        {
            age: 25,
            normal_height_median: 86.5,
            stunting_threshold: 79.9,
            malnutrition_weight: 5.9,
            obesity_weight: 11.4,
        },
        {
            age: 26,
            normal_height_median: 87.3,
            stunting_threshold: 80.7,
            malnutrition_weight: 6.0,
            obesity_weight: 11.7,
        },
        {
            age: 27,
            normal_height_median: 88.0,
            stunting_threshold: 81.4,
            malnutrition_weight: 6.2,
            obesity_weight: 12.0,
        },
        {
            age: 28,
            normal_height_median: 88.8,
            stunting_threshold: 82.2,
            malnutrition_weight: 6.3,
            obesity_weight: 12.2,
        },
        {
            age: 29,
            normal_height_median: 89.6,
            stunting_threshold: 82.9,
            malnutrition_weight: 6.5,
            obesity_weight: 12.5,
        },
        {
            age: 30,
            normal_height_median: 90.4,
            stunting_threshold: 83.7,
            malnutrition_weight: 6.6,
            obesity_weight: 12.8,
        },
        {
            age: 31,
            normal_height_median: 91.2,
            stunting_threshold: 84.4,
            malnutrition_weight: 6.7,
            obesity_weight: 13.1,
        },
        {
            age: 32,
            normal_height_median: 92.0,
            stunting_threshold: 85.1,
            malnutrition_weight: 6.9,
            obesity_weight: 13.4,
        },
        {
            age: 33,
            normal_height_median: 92.8,
            stunting_threshold: 85.9,
            malnutrition_weight: 7.0,
            obesity_weight: 13.6,
        },
        {
            age: 34,
            normal_height_median: 93.5,
            stunting_threshold: 86.6,
            malnutrition_weight: 7.2,
            obesity_weight: 13.9,
        },
        {
            age: 35,
            normal_height_median: 94.3,
            stunting_threshold: 87.4,
            malnutrition_weight: 7.3,
            obesity_weight: 14.2,
        },
        {
            age: 36,
            normal_height_median: 95.1,
            stunting_threshold: 88.1,
            malnutrition_weight: 7.4,
            obesity_weight: 14.5,
        },
        {
            age: 37,
            normal_height_median: 95.7,
            stunting_threshold: 88.6,
            malnutrition_weight: 7.6,
            obesity_weight: 14.8,
        },
        {
            age: 38,
            normal_height_median: 96.4,
            stunting_threshold: 89.1,
            malnutrition_weight: 7.7,
            obesity_weight: 15.0,
        },
        {
            age: 39,
            normal_height_median: 97.0,
            stunting_threshold: 89.7,
            malnutrition_weight: 7.9,
            obesity_weight: 15.3,
        },
        {
            age: 40,
            normal_height_median: 97.6,
            stunting_threshold: 90.2,
            malnutrition_weight: 8.0,
            obesity_weight: 15.6,
        },
        {
            age: 41,
            normal_height_median: 98.3,
            stunting_threshold: 90.7,
            malnutrition_weight: 8.1,
            obesity_weight: 15.9,
        },
        {
            age: 42,
            normal_height_median: 98.9,
            stunting_threshold: 91.2,
            malnutrition_weight: 8.3,
            obesity_weight: 16.2,
        },
        {
            age: 43,
            normal_height_median: 99.5,
            stunting_threshold: 91.8,
            malnutrition_weight: 8.4,
            obesity_weight: 16.4,
        },
        {
            age: 44,
            normal_height_median: 100.2,
            stunting_threshold: 92.3,
            malnutrition_weight: 8.6,
            obesity_weight: 16.7,
        },
        {
            age: 45,
            normal_height_median: 100.8,
            stunting_threshold: 92.8,
            malnutrition_weight: 8.7,
            obesity_weight: 17.0,
        },
        {
            age: 46,
            normal_height_median: 101.4,
            stunting_threshold: 93.4,
            malnutrition_weight: 8.8,
            obesity_weight: 17.3,
        },
        {
            age: 47,
            normal_height_median: 102.1,
            stunting_threshold: 93.9,
            malnutrition_weight: 9.0,
            obesity_weight: 17.6,
        },
        {
            age: 48,
            normal_height_median: 102.7,
            stunting_threshold: 94.4,
            malnutrition_weight: 9.1,
            obesity_weight: 17.8,
        },
        {
            age: 49,
            normal_height_median: 103.3,
            stunting_threshold: 94.9,
            malnutrition_weight: 9.3,
            obesity_weight: 18.1,
        },
        {
            age: 50,
            normal_height_median: 103.9,
            stunting_threshold: 95.3,
            malnutrition_weight: 9.4,
            obesity_weight: 18.4,
        },
        {
            age: 51,
            normal_height_median: 104.5,
            stunting_threshold: 95.8,
            malnutrition_weight: 9.5,
            obesity_weight: 18.7,
        },
        {
            age: 52,
            normal_height_median: 105.1,
            stunting_threshold: 96.3,
            malnutrition_weight: 9.7,
            obesity_weight: 19.0,
        },
        {
            age: 53,
            normal_height_median: 105.7,
            stunting_threshold: 96.7,
            malnutrition_weight: 9.8,
            obesity_weight: 19.2,
        },
        {
            age: 54,
            normal_height_median: 106.3,
            stunting_threshold: 97.2,
            malnutrition_weight: 10.0,
            obesity_weight: 19.5,
        },
        {
            age: 55,
            normal_height_median: 107.0,
            stunting_threshold: 97.7,
            malnutrition_weight: 10.1,
            obesity_weight: 19.8,
        },
        {
            age: 56,
            normal_height_median: 107.6,
            stunting_threshold: 98.1,
            malnutrition_weight: 10.2,
            obesity_weight: 20.1,
        },
        {
            age: 57,
            normal_height_median: 108.2,
            stunting_threshold: 98.6,
            malnutrition_weight: 10.4,
            obesity_weight: 20.4,
        },
        {
            age: 58,
            normal_height_median: 108.8,
            stunting_threshold: 99.1,
            malnutrition_weight: 10.5,
            obesity_weight: 20.6,
        },
        {
            age: 59,
            normal_height_median: 109.4,
            stunting_threshold: 99.5,
            malnutrition_weight: 10.7,
            obesity_weight: 20.9,
        },
        {
            age: 60,
            normal_height_median: 110.0,
            stunting_threshold: 100.0,
            malnutrition_weight: 10.8,
            obesity_weight: 21.2,
        },
    ],
};
